# Generated by Django 6.0.5 on 2026-05-17 16:31

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filled_data', models.JSONField(default=dict)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.output_upload_path)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_documents', to='templates_app.template')),
            ],
            options={
                'verbose_name': 'Заполненный документ',
                'verbose_name_plural': 'Заполненные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
